// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'register_visa_web_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CHECK_MARK = 'assets/icons/check_mark.png';
  static const String CLOSE_RED = 'assets/icons/close_red.png';
  static const String DATE = 'assets/icons/date.png';
  static const String DOCUMENT = 'assets/icons/document.png';
  static const String FILL_STAR = 'assets/icons/fill_star.png';
  static const String LOCATION = 'assets/icons/location.png';
  static const String PEOPLE = 'assets/icons/people.png';
}
