// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'register_visa_web_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String OUTFIT_BLACK = 'Outfit-Black';
  static const String OUTFIT_BOLD = 'Outfit-Bold';
  static const String OUTFIT_EXTRABOLD = 'Outfit-ExtraBold';
  static const String OUTFIT_EXTRALIGHT = 'Outfit-ExtraLight';
  static const String OUTFIT_LIGHT = 'Outfit-Light';
  static const String OUTFIT_MEDIUM = 'Outfit-Medium';
  static const String OUTFIT_REGULAR = 'Outfit-Regular';
  static const String OUTFIT_SEMIBOLD = 'Outfit-SemiBold';
  static const String OUTFIT_THIN = 'Outfit-Thin';
}
