import 'package:country_pickers/country.dart';

final List<Country> allCountryList = [
  // A
  Country(name: "Afghanistan", isoCode: "AF", iso3Code: "AFG", phoneCode: ""),
  Country(name: "Albania", isoCode: "AL", iso3Code: "ALB", phoneCode: ""),
  Country(name: "Algeria", isoCode: "DZ", iso3Code: "DZA", phoneCode: ""),
  Country(name: "Andorra", isoCode: "AD", iso3Code: "AND", phoneCode: ""),
  Country(name: "Angola", isoCode: "AO", iso3Code: "AGO", phoneCode: ""),
  Country(
    name: "Antigua and Barbuda",
    isoCode: "AG",
    iso3Code: "ATG",
    phoneCode: "",
  ),
  Country(name: "Argentina", isoCode: "AR", iso3Code: "ARG", phoneCode: ""),
  Country(name: "Armenia", isoCode: "AM", iso3Code: "ARM", phoneCode: ""),
  Country(name: "Australia", isoCode: "AU", iso3Code: "AUS", phoneCode: ""),
  Country(name: "Austria", isoCode: "AT", iso3Code: "AUT", phoneCode: ""),
  Country(name: "Azerbaijan", isoCode: "AZ", iso3Code: "AZE", phoneCode: ""),

  // B
  Country(name: "Bahamas", isoCode: "BS", iso3Code: "BHS", phoneCode: ""),
  Country(name: "Bahrain", isoCode: "BH", iso3Code: "BHR", phoneCode: ""),
  Country(name: "Bangladesh", isoCode: "BD", iso3Code: "BGD", phoneCode: ""),
  Country(name: "Barbados", isoCode: "BB", iso3Code: "BRB", phoneCode: ""),
  Country(name: "Belarus", isoCode: "BY", iso3Code: "BLR", phoneCode: ""),
  Country(name: "Belgium", isoCode: "BE", iso3Code: "BEL", phoneCode: ""),
  Country(name: "Belize", isoCode: "BZ", iso3Code: "BLZ", phoneCode: ""),
  Country(name: "Benin", isoCode: "BJ", iso3Code: "BEN", phoneCode: ""),
  Country(name: "Bhutan", isoCode: "BT", iso3Code: "BTN", phoneCode: ""),
  Country(name: "Bolivia", isoCode: "BO", iso3Code: "BOL", phoneCode: ""),
  Country(
    name: "Bosnia and Herzegovina",
    isoCode: "BA",
    iso3Code: "BIH",
    phoneCode: "",
  ),
  Country(name: "Botswana", isoCode: "BW", iso3Code: "BWA", phoneCode: ""),
  Country(name: "Brazil", isoCode: "BR", iso3Code: "BRA", phoneCode: ""),
  Country(name: "Brunei", isoCode: "BN", iso3Code: "BRN", phoneCode: ""),
  Country(name: "Bulgaria", isoCode: "BG", iso3Code: "BGR", phoneCode: ""),
  Country(name: "Burkina Faso", isoCode: "BF", iso3Code: "BFA", phoneCode: ""),
  Country(name: "Burundi", isoCode: "BI", iso3Code: "BDI", phoneCode: ""),

  // C
  Country(name: "Cambodia", isoCode: "KH", iso3Code: "KHM", phoneCode: ""),
  Country(name: "Cameroon", isoCode: "CM", iso3Code: "CMR", phoneCode: ""),
  Country(name: "Canada", isoCode: "CA", iso3Code: "CAN", phoneCode: ""),
  Country(name: "Cape Verde", isoCode: "CV", iso3Code: "CPV", phoneCode: ""),
  Country(
    name: "Central African Republic",
    isoCode: "CF",
    iso3Code: "CAF",
    phoneCode: "",
  ),
  Country(name: "Chad", isoCode: "TD", iso3Code: "TCD", phoneCode: ""),
  Country(name: "Chile", isoCode: "CL", iso3Code: "CHL", phoneCode: ""),
  Country(name: "China", isoCode: "CN", iso3Code: "CHN", phoneCode: ""),
  Country(name: "Colombia", isoCode: "CO", iso3Code: "COL", phoneCode: ""),
  Country(name: "Comoros", isoCode: "KM", iso3Code: "COM", phoneCode: ""),
  Country(
    name: "Congo (Brazzaville)",
    isoCode: "CG",
    iso3Code: "COG",
    phoneCode: "",
  ),
  Country(
    name: "Congo (Kinshasa)",
    isoCode: "CD",
    iso3Code: "COD",
    phoneCode: "",
  ),
  Country(name: "Costa Rica", isoCode: "CR", iso3Code: "CRI", phoneCode: ""),
  Country(name: "Croatia", isoCode: "HR", iso3Code: "HRV", phoneCode: ""),
  Country(name: "Cuba", isoCode: "CU", iso3Code: "CUB", phoneCode: ""),
  Country(name: "Cyprus", isoCode: "CY", iso3Code: "CYP", phoneCode: ""),
  Country(
    name: "Czech Republic",
    isoCode: "CZ",
    iso3Code: "CZE",
    phoneCode: "",
  ),
  Country(name: "Denmark", isoCode: "DK", iso3Code: "DNK", phoneCode: ""),
  Country(name: "Djibouti", isoCode: "DJ", iso3Code: "DJI", phoneCode: ""),
  Country(name: "Dominica", isoCode: "DM", iso3Code: "DMA", phoneCode: ""),
  Country(
    name: "Dominican Republic",
    isoCode: "DO",
    iso3Code: "DOM",
    phoneCode: "",
  ),
  Country(name: "Ecuador", isoCode: "EC", iso3Code: "ECU", phoneCode: ""),
  Country(name: "Egypt", isoCode: "EG", iso3Code: "EGY", phoneCode: ""),
  Country(name: "El Salvador", isoCode: "SV", iso3Code: "SLV", phoneCode: ""),
  Country(
    name: "Equatorial Guinea",
    isoCode: "GQ",
    iso3Code: "GNQ",
    phoneCode: "",
  ),
  Country(name: "Eritrea", isoCode: "ER", iso3Code: "ERI", phoneCode: ""),
  Country(name: "Estonia", isoCode: "EE", iso3Code: "EST", phoneCode: ""),
  Country(name: "Eswatini", isoCode: "SZ", iso3Code: "SWZ", phoneCode: ""),
  Country(name: "Ethiopia", isoCode: "ET", iso3Code: "ETH", phoneCode: ""),
  Country(name: "Fiji", isoCode: "FJ", iso3Code: "FJI", phoneCode: ""),
  Country(name: "Finland", isoCode: "FI", iso3Code: "FIN", phoneCode: ""),
  Country(name: "France", isoCode: "FR", iso3Code: "FRA", phoneCode: ""),
  Country(name: "Gabon", isoCode: "GA", iso3Code: "GAB", phoneCode: ""),
  Country(name: "Gambia", isoCode: "GM", iso3Code: "GMB", phoneCode: ""),
  Country(name: "Georgia", isoCode: "GE", iso3Code: "GEO", phoneCode: ""),
  Country(name: "Germany", isoCode: "DE", iso3Code: "DEU", phoneCode: ""),
  Country(name: "Ghana", isoCode: "GH", iso3Code: "GHA", phoneCode: ""),
  Country(name: "Greece", isoCode: "GR", iso3Code: "GRC", phoneCode: ""),
  Country(name: "Grenada", isoCode: "GD", iso3Code: "GRD", phoneCode: ""),
  Country(name: "Guatemala", isoCode: "GT", iso3Code: "GTM", phoneCode: ""),
  Country(name: "Guinea", isoCode: "GN", iso3Code: "GIN", phoneCode: ""),
  Country(name: "Guinea-Bissau", isoCode: "GW", iso3Code: "GNB", phoneCode: ""),
  Country(name: "Guyana", isoCode: "GY", iso3Code: "GUY", phoneCode: ""),
  Country(name: "Haiti", isoCode: "HT", iso3Code: "HTI", phoneCode: ""),
  Country(name: "Honduras", isoCode: "HN", iso3Code: "HND", phoneCode: ""),
  Country(name: "Hungary", isoCode: "HU", iso3Code: "HUN", phoneCode: ""),
  Country(name: "Iceland", isoCode: "IS", iso3Code: "ISL", phoneCode: ""),
  Country(name: "India", isoCode: "IN", iso3Code: "IND", phoneCode: ""),
  Country(name: "Indonesia", isoCode: "ID", iso3Code: "IDN", phoneCode: ""),
  Country(name: "Iran", isoCode: "IR", iso3Code: "IRN", phoneCode: ""),
  Country(name: "Iraq", isoCode: "IQ", iso3Code: "IRQ", phoneCode: ""),
  Country(name: "Ireland", isoCode: "IE", iso3Code: "IRL", phoneCode: ""),
  Country(name: "Israel", isoCode: "IL", iso3Code: "ISR", phoneCode: ""),
  Country(name: "Italy", isoCode: "IT", iso3Code: "ITA", phoneCode: ""),
  Country(name: "Jamaica", isoCode: "JM", iso3Code: "JAM", phoneCode: ""),
  Country(name: "Japan", isoCode: "JP", iso3Code: "JPN", phoneCode: ""),
  Country(name: "Jordan", isoCode: "JO", iso3Code: "JOR", phoneCode: ""),
  Country(name: "Kazakhstan", isoCode: "KZ", iso3Code: "KAZ", phoneCode: ""),
  Country(name: "Kenya", isoCode: "KE", iso3Code: "KEN", phoneCode: ""),
  Country(name: "Kiribati", isoCode: "KI", iso3Code: "KIR", phoneCode: ""),
  Country(name: "Kuwait", isoCode: "KW", iso3Code: "KWT", phoneCode: ""),
  Country(name: "Kyrgyzstan", isoCode: "KG", iso3Code: "KGZ", phoneCode: ""),
  Country(name: "Laos", isoCode: "LA", iso3Code: "LAO", phoneCode: ""),
  Country(name: "Latvia", isoCode: "LV", iso3Code: "LVA", phoneCode: ""),
  Country(name: "Lebanon", isoCode: "LB", iso3Code: "LBN", phoneCode: ""),
  Country(name: "Lesotho", isoCode: "LS", iso3Code: "LSO", phoneCode: ""),
  Country(name: "Liberia", isoCode: "LR", iso3Code: "LBR", phoneCode: ""),
  Country(name: "Libya", isoCode: "LY", iso3Code: "LBY", phoneCode: ""),
  Country(name: "Liechtenstein", isoCode: "LI", iso3Code: "LIE", phoneCode: ""),
  Country(name: "Lithuania", isoCode: "LT", iso3Code: "LTU", phoneCode: ""),
  Country(name: "Luxembourg", isoCode: "LU", iso3Code: "LUX", phoneCode: ""),
  Country(name: "Madagascar", isoCode: "MG", iso3Code: "MDG", phoneCode: ""),
  Country(name: "Malawi", isoCode: "MW", iso3Code: "MWI", phoneCode: ""),
  Country(name: "Malaysia", isoCode: "MY", iso3Code: "MYS", phoneCode: ""),
  Country(name: "Maldives", isoCode: "MV", iso3Code: "MDV", phoneCode: ""),
  Country(name: "Mali", isoCode: "ML", iso3Code: "MLI", phoneCode: ""),
  Country(name: "Malta", isoCode: "MT", iso3Code: "MLT", phoneCode: ""),
  Country(
    name: "Marshall Islands",
    isoCode: "MH",
    iso3Code: "MHL",
    phoneCode: "",
  ),
  Country(name: "Mauritania", isoCode: "MR", iso3Code: "MRT", phoneCode: ""),
  Country(name: "Mauritius", isoCode: "MU", iso3Code: "MUS", phoneCode: ""),
  Country(name: "Mexico", isoCode: "MX", iso3Code: "MEX", phoneCode: ""),
  Country(name: "Micronesia", isoCode: "FM", iso3Code: "FSM", phoneCode: ""),
  Country(name: "Moldova", isoCode: "MD", iso3Code: "MDA", phoneCode: ""),
  Country(name: "Monaco", isoCode: "MC", iso3Code: "MCO", phoneCode: ""),
  Country(name: "Mongolia", isoCode: "MN", iso3Code: "MNG", phoneCode: ""),
  Country(name: "Montenegro", isoCode: "ME", iso3Code: "MNE", phoneCode: ""),
  Country(name: "Morocco", isoCode: "MA", iso3Code: "MAR", phoneCode: ""),
  Country(name: "Mozambique", isoCode: "MZ", iso3Code: "MOZ", phoneCode: ""),
  Country(name: "Myanmar", isoCode: "MM", iso3Code: "MMR", phoneCode: ""),
  Country(name: "Namibia", isoCode: "NA", iso3Code: "NAM", phoneCode: ""),
  Country(name: "Nauru", isoCode: "NR", iso3Code: "NRU", phoneCode: ""),
  Country(name: "Nepal", isoCode: "NP", iso3Code: "NPL", phoneCode: ""),
  Country(name: "Netherlands", isoCode: "NL", iso3Code: "NLD", phoneCode: ""),
  Country(name: "New Zealand", isoCode: "NZ", iso3Code: "NZL", phoneCode: ""),
  Country(name: "Nicaragua", isoCode: "NI", iso3Code: "NIC", phoneCode: ""),
  Country(name: "Niger", isoCode: "NE", iso3Code: "NER", phoneCode: ""),
  Country(name: "Nigeria", isoCode: "NG", iso3Code: "NGA", phoneCode: ""),
  Country(name: "North Korea", isoCode: "KP", iso3Code: "PRK", phoneCode: ""),
  Country(
    name: "North Macedonia",
    isoCode: "MK",
    iso3Code: "MKD",
    phoneCode: "",
  ),
  Country(name: "Norway", isoCode: "NO", iso3Code: "NOR", phoneCode: ""),
  Country(name: "Oman", isoCode: "OM", iso3Code: "OMN", phoneCode: ""),
  Country(name: "Pakistan", isoCode: "PK", iso3Code: "PAK", phoneCode: ""),
  Country(name: "Palau", isoCode: "PW", iso3Code: "PLW", phoneCode: ""),
  Country(name: "Panama", isoCode: "PA", iso3Code: "PAN", phoneCode: ""),
  Country(
    name: "Papua New Guinea",
    isoCode: "PG",
    iso3Code: "PNG",
    phoneCode: "",
  ),
  Country(name: "Paraguay", isoCode: "PY", iso3Code: "PRY", phoneCode: ""),
  Country(name: "Peru", isoCode: "PE", iso3Code: "PER", phoneCode: ""),
  Country(name: "Philippines", isoCode: "PH", iso3Code: "PHL", phoneCode: ""),
  Country(name: "Poland", isoCode: "PL", iso3Code: "POL", phoneCode: ""),
  Country(name: "Portugal", isoCode: "PT", iso3Code: "PRT", phoneCode: ""),
  Country(name: "Qatar", isoCode: "QA", iso3Code: "QAT", phoneCode: ""),
  Country(name: "Romania", isoCode: "RO", iso3Code: "ROU", phoneCode: ""),
  Country(name: "Russia", isoCode: "RU", iso3Code: "RUS", phoneCode: ""),
  Country(name: "Rwanda", isoCode: "RW", iso3Code: "RWA", phoneCode: ""),
  Country(name: "Saudi Arabia", isoCode: "SA", iso3Code: "SAU", phoneCode: ""),
  Country(name: "Senegal", isoCode: "SN", iso3Code: "SEN", phoneCode: ""),
  Country(name: "Serbia", isoCode: "RS", iso3Code: "SRB", phoneCode: ""),
  Country(name: "Seychelles", isoCode: "SC", iso3Code: "SYC", phoneCode: ""),
  Country(name: "Sierra Leone", isoCode: "SL", iso3Code: "SLE", phoneCode: ""),
  Country(name: "Singapore", isoCode: "SG", iso3Code: "SGP", phoneCode: ""),
  Country(name: "Slovakia", isoCode: "SK", iso3Code: "SVK", phoneCode: ""),
  Country(name: "Slovenia", isoCode: "SI", iso3Code: "SVN", phoneCode: ""),
  Country(name: "Somalia", isoCode: "SO", iso3Code: "SOM", phoneCode: ""),
  Country(name: "South Africa", isoCode: "ZA", iso3Code: "ZAF", phoneCode: ""),
  Country(name: "South Korea", isoCode: "KR", iso3Code: "KOR", phoneCode: ""),
  Country(name: "Spain", isoCode: "ES", iso3Code: "ESP", phoneCode: ""),
  Country(name: "Sri Lanka", isoCode: "LK", iso3Code: "LKA", phoneCode: ""),
  Country(name: "Sudan", isoCode: "SD", iso3Code: "SDN", phoneCode: ""),
  Country(name: "Suriname", isoCode: "SR", iso3Code: "SUR", phoneCode: ""),
  Country(name: "Sweden", isoCode: "SE", iso3Code: "SWE", phoneCode: ""),
  Country(name: "Switzerland", isoCode: "CH", iso3Code: "CHE", phoneCode: ""),
  Country(name: "Syria", isoCode: "SY", iso3Code: "SYR", phoneCode: ""),
  Country(name: "Taiwan", isoCode: "TW", iso3Code: "TWN", phoneCode: ""),
  Country(name: "Tajikistan", isoCode: "TJ", iso3Code: "TJK", phoneCode: ""),
  Country(name: "Tanzania", isoCode: "TZ", iso3Code: "TZA", phoneCode: ""),
  Country(name: "Thailand", isoCode: "TH", iso3Code: "THA", phoneCode: ""),
  Country(name: "Togo", isoCode: "TG", iso3Code: "TGO", phoneCode: ""),
  Country(name: "Tonga", isoCode: "TO", iso3Code: "TON", phoneCode: ""),
  Country(name: "Tunisia", isoCode: "TN", iso3Code: "TUN", phoneCode: ""),
  Country(name: "Turkey", isoCode: "TR", iso3Code: "TUR", phoneCode: ""),
  Country(name: "Uganda", isoCode: "UG", iso3Code: "UGA", phoneCode: ""),
  Country(name: "Ukraine", isoCode: "UA", iso3Code: "UKR", phoneCode: ""),
  Country(
    name: "United Arab Emirates",
    isoCode: "AE",
    iso3Code: "ARE",
    phoneCode: "",
  ),
  Country(
    name: "United Kingdom",
    isoCode: "GB",
    iso3Code: "GBR",
    phoneCode: "",
  ),
  Country(name: "United States", isoCode: "US", iso3Code: "USA", phoneCode: ""),
  Country(name: "Uruguay", isoCode: "UY", iso3Code: "URY", phoneCode: ""),
  Country(name: "Uzbekistan", isoCode: "UZ", iso3Code: "UZB", phoneCode: ""),
  Country(name: "Vanuatu", isoCode: "VU", iso3Code: "VUT", phoneCode: ""),
  Country(name: "Vatican City", isoCode: "VA", iso3Code: "VAT", phoneCode: ""),
  Country(name: "Venezuela", isoCode: "VE", iso3Code: "VEN", phoneCode: ""),
  Country(name: "Vietnam", isoCode: "VN", iso3Code: "VNM", phoneCode: ""),
  Country(name: "Yemen", isoCode: "YE", iso3Code: "YEM", phoneCode: ""),
  Country(name: "Zambia", isoCode: "ZM", iso3Code: "ZMB", phoneCode: ""),
  Country(name: "Zimbabwe", isoCode: "ZW", iso3Code: "ZWE", phoneCode: ""),
];

Country? countryFromName(String? name) {
  if (name == null || name.isEmpty) return null;
  final n = name.trim();
  try {
    return allCountryList.firstWhere((c) => c.name == n || c.isoCode == n || c.iso3Code == n);
  } catch (_) {
    return null;
  }
}
